### DISCUSSION TITLE
What do you do to enable testing for all circleci jobs?

### DISCUSSION THREAD

**Discussion by midenok** [mydumper/mydumper#1383] [Q&A]
I did (I know there is more "right" way to do this):

```diff
--- .circleci/circleci_config_builder.sh
+++ .circleci/circleci_config_builder.sh
@@ -378,7 +378,7 @@ echo "
     parameters:
       test:
         type: boolean
-        default: false
+        default: true
       e:
         type: string
         default: ${all_os[${os}_0]}_${all_vendors[${vendor}_0]}
@@ -407,7 +407,7 @@ echo "
     parameters:
       test:
         type: boolean
-        default: false
+        default: true
       e:
         type: string
         default: ${all_os[${os}_0]}
```

And it did not run container for server. Though I see it generates 2nd image like this:

```
  el8_percona80:
    docker:
    - image: mydumper/mydumper-builder-el8
      environment:
        MYSQL_HOST: 127.0.0.1
        MYSQL_DB: mate
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: true
        MYSQL_PASSWORD:
    - image: percona:8
      command: mysqld
      environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: /tmp/src/mydumper
```

But it doesn't run percona:8 for el8. Why?
