### ISSUE TITLE
[BUG] Replication position broken on slave after backup/restore

### ISSUE THREAD

**Issue by Nopius** [mydumper/mydumper#1370]
**Describe the bug**
I was using mydumper to make a full logical backup from the slave running on Percona MySQL version 5.7.38-41-log.
I didn't stop the slave threads while running mydumper. 
Slave runs single threaded replication (no MTS).

I restored slave from the backup and configured master_log_file and master_log_pos according to the 'metadata' from the backup:

```
..
[replication]
# relay_master_log_file = 'notifications2-binlog.000328'
# exec_master_log_pos = 125652943
...

```
After starting the slave I get  Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY

**To Reproduce**

Command executed:
* don't stop slave
* run dump/restore on a slave
* mydumper --outputdir="/backup" --routines --events --triggers --compress --build-empty-files --use-savepoints --rows=1000000 --less-locking -v 3 -p xxx
* myloader --directory /backup/  --threads=4 --verbose 3 -o -p xxx
* take relay_master_log_file and exec_master_log_pos from the 'metadata' from backup and set the master_log_file and master_log_pos accordingly
* start slave

What mydumper and myloader version has been used?

I tried different versions of mydumper, starting from 0.14.3, then it was found broken and I upraded to the latest release from the site 0.15.1-3, which also was broken, then I downgraded to version 0.10.7 and it was fine:

- mydumper-0.14.3-1.el7.x86_64.rpm (BROKEN)
- mydumper-0.15.1-3.el7.x86_64.rpm (BROKEN)
- mydumper-0.10.7-7.el7.x86_64.rpm (OK)

**Expected behavior**

**Log**
```
# Started dump at: 2023-12-13 12:47:42
[master]
# Channel_Name = '' # It can be use to setup replication FOR CHANNEL
File = notifications1-binlog.195726
Position = 51915857
Executed_Gtid_Set =

[replication]
# relay_master_log_file = 'notifications2-binlog.000328'
# exec_master_log_pos = 125652943
# Executed_Gtid_Set =
# Slave_IO_State = 'Waiting for master to send event'
# Master_Host = 'notifications2.domain.name'
# Master_User = 'repl'
# Master_Port = 3306
# Connect_Retry = 60
# Master_Log_File = 'notifications2-binlog.000334'
# Read_Master_Log_Pos = 137651819
# Relay_Log_File = 'mysqld-relay-bin.000958'
# Relay_Log_Pos = 125653180
# Relay_Master_Log_File = 'notifications2-binlog.000328'
# Slave_IO_Running = 'Yes'
# Slave_SQL_Running = 'Yes'
# Replicate_Do_DB = ''
# Replicate_Ignore_DB = ''
# Replicate_Do_Table = ''
# Replicate_Ignore_Table = ''
# Replicate_Wild_Do_Table = ''
# Replicate_Wild_Ignore_Table = ''
# Last_Errno = 0
# Last_Error = ''
# Skip_Counter = 0
# Exec_Master_Log_Pos = 125652943
# Relay_Log_Space = 1081671108
# Until_Condition = 'None'
# Until_Log_File = ''
# Until_Log_Pos = 0
# Master_SSL_Allowed = 'No'
...
mysql> change master to master_log_file = 'notifications2-binlog.000328';
Query OK, 0 rows affected, 1 warning (0.03 sec)

mysql> change master to master_log_pos = 125652943;
Query OK, 0 rows affected (0.02 sec)

mysql> start slave ;
Query OK, 0 rows affected (0.00 sec)

mysql> show slave status\G                                                                                                                                                                             
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: ***
                  Master_User: ***
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: notifications2-binlog.000600
          Read_Master_Log_Pos: 151895791
               Relay_Log_File: mysqld-relay-bin.000002
                Relay_Log_Pos: 688
        Relay_Master_Log_File: notifications2-binlog.000328
             Slave_IO_Running: Yes
            Slave_SQL_Running: No
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 1062
                   Last_Error: Could not execute Write_rows event on table notifications.broadcast_group_delivery_normalized; Duplicate entry '10059863194-88076012' for key 'broadcast_id', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log notifications2-binlog.000328, end_log_pos 125653932
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 125653299
              Relay_Log_Space: 42943086115
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 1062
               Last_SQL_Error: Could not execute Write_rows event on table notifications.broadcast_group_delivery_normalized; Duplicate entry '10059863194-88076012' for key 'broadcast_id', Error_code: 1062; han$ler error HA_ERR_FOUND_DUPP_KEY; the event's master log notifications2-binlog.000328, end_log_pos 125653932
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 4
                  Master_UUID: 9899f708-9734-11ee-a505-52540047b0f5
             Master_Info_File: /opt2/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State:
      ...
```
**Backup**
There is one table with Unique Key, but no explicitly defined PRIMARY KEY  with high rate of updates and this table has the complains about DUPLICATE KEY:
```
CREATE TABLE `broadcast_group_delivery_normalized` (
  `broadcast_id` bigint(20) unsigned NOT NULL,
  `device_id` int(11) unsigned NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `submitted` timestamp NULL DEFAULT NULL,
  `reject_reason` varchar(100) DEFAULT NULL,
  UNIQUE KEY `broadcast_id` (`broadcast_id`,`device_id`),
  KEY `device_id` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
**How to repeat**

* Create a master-slave configuration on MySQL 5.7 without GTID
* Create a table with the structure above (UNIQUE KEY and no PRIMARY)
* Generate heavy writes to this table
* Start a backup on slave with the parameters above, without stopping it, wait for competion
* Restore slave from the backup with the parameters above to the new slave instance (and new server-id)
* Restore slave replication according to the metadata exec_master_log_pos and relay_master_log_file
* Start slave and check the status

**Environment (please complete the following information):**
 - OS version: OracleLinux 7.7
 - MyDumper version: 0.15.1
 - MySQL version on slave: 5.7.38-41-log from Percona

**Additional context**
I took mydumper the RPMs on a GitHub release page
