### ISSUE TITLE
[BUG] Cannot connect to database via non-standard socket path

### ISSUE THREAD

**Issue by Zankaria** [mydumper/mydumper#1586]
**Describe the bug**
Attepting to connect to a database with a socket in a non-standard path returns a critical faliure

**To Reproduce**
Command executed:
`sudo mydumper --socket local-instances/mysql-measure/mysql/mysql.sock`

**Expected behavior**
mydumper should connect or at least return another kind of error (eg, missing password, bad user, something appropriate if there's a different error)

**Environment (please complete the following information):**
 - OS version: Up to date Manjaro
 - MyDumper version: `mydumper v0.16.3-6, built against MariaDB 11.4.2 with SSL support`

**Additional context**
The socket in question has a non-standard path because it's a volume mounted in a local directory from a container. It should be reproducible with this docker compose snippet
```
services:
 #MySQL Service
  db:
    image: mysql:8.0.35
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vichan
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./local-instances/${INSTANCE:-0}/mysql:/var/lib/mysql
```
It can be started as such:
```
mkdir -p /local-instances/mysql-measure/mysql:/var/lib/mysql
INSTANCE=mysql-measure docker compose up -d db
```

The weirdness of the setup is due to the fact that it's meant for testing. The objective behind this whole ordeal is to benchmark mydumper against mysqldump on some of our production backups to see if it's sufficiently fast to solve some lag issues we've been experiencing for a while in prod.
