### ISSUE TITLE
On MySQL 8 slave, using mydumper causes ‘seconds behind master’.

### ISSUE THREAD

**Issue by billy522** [mydumper/mydumper#1705]
**Describe**
My original environment was MySQL 5.7.34, and the version of mydumper used was v0.16.7-5.
Before the MySQL upgrade, the backup behavior was normal, and there were no SBM issues.
But after upgrading MySQL to 8.0.37 (with the mydumper version unchanged), SBM occurs during the backup process every day.

I want to confirm what the root cause of this change is.
I have already used the –less-locking option and am not considering the –no-locks option for now.
What options can I use to ensure that my slave, during the backup, doesn’t experience “seconds behind master” like it did with MySQL 5.7?

**information_schema.innodb_trx**
```
mysql> select trx_id,trx_state,trx_requested_lock_id,trx_query,trx_operation_state,trx_isolation_level from information_schema.innodb_trx;
+-----------------+-----------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| trx_id          | trx_state | trx_requested_lock_id | trx_query                                                                                                                     | trx_operation_state | trx_isolation_level |
+-----------------+-----------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| 421974015710688 | RUNNING   | NULL                  | SELECT /*!40001 SQL_NO_CACHE */ * FROM `db`.`aaa`  WHERE (`id` IS NULL OR(0 <= `id` AND `id` <= 29999999)) | NULL                | REPEATABLE READ     |
| 421974015709880 | RUNNING   | NULL                  | SELECT /*!40001 SQL_NO_CACHE */ * FROM `db`.`bbb`                                                      | fetching rows       | REPEATABLE READ     |
| 421974015708264 | RUNNING   | NULL                  | SELECT /*!40001 SQL_NO_CACHE */ * FROM `db`.`aaa`  WHERE (90000000 <= `id` AND `id` <= 119999999)          | fetching rows       | REPEATABLE READ     |
| 421974015706648 | RUNNING   | NULL                  | SELECT /*!40001 SQL_NO_CACHE */ * FROM `db`.`aaa`  WHERE (60000000 <= `id` AND `id` <= 89999999)           | fetching rows       | REPEATABLE READ     |
+-----------------+-----------+-----------------------+-------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
4 rows in set (0.00 sec)
```

**Backup command**
```
mydumper --defaults-file=/root/.my.cnf --socket=/var/run/mysqld/mysqld.sock --rows=30000000 --outputdir=${backup_base_dir}/$(date +%Y%m%d) --verbose=3 --kill-long-queries --chunk-filesize=5120 --build-empty-files --events --routines --triggers --compress --less-locking -L ${backup_base_dir}/mydumper.log
```

**Environment (please complete the following information):**
 - OS version: CentOS Linux release 7.9.2009 (Core)
 - MyDumper version: mydumper v0.16.7-5, built against MySQL 5.7.44-48 with SSL support

**Additional context**
Thank you very much for your help. If you need any information from me, please feel free to ask.

**Comment by billy522** [comment]
** mydumper.log **
```2024-12-19 03:39:43 [INFO] - Acquiring DDL lock
2024-12-19 03:39:43 [INFO] - LOCK INSTANCE FOR BACKUP: OK
2024-12-19 03:39:43 [INFO] - Acquiring Global lock
2024-12-19 03:39:43 [INFO] - FLUSH NO_WRITE_TO_BINLOG TABLES: OK
2024-12-19 03:39:43 [INFO] - FLUSH TABLES WITH READ LOCK: OK
2024-12-19 03:39:43 [INFO] - conf created
2024-12-19 03:39:43 [INFO] - End job creation
2024-12-19 03:39:43 [INFO] - Creating workers
2024-12-19 03:39:43 [INFO] - Starting Non-InnoDB tables
2024-12-19 03:39:43 [INFO] - Thread 3: connected using MySQL connection ID 32491
2024-12-19 03:39:43 [INFO] - Thread 4: connected using MySQL connection ID 32493
2024-12-19 03:39:43 [INFO] - Thread 2: connected using MySQL connection ID 32492
2024-12-19 03:39:43 [INFO] - Thread 1: connected using MySQL connection ID 32494
....
....
....
2024-12-19 06:24:26 [INFO] - Releasing DDL lock
2024-12-19 06:24:26 [INFO] - UNLOCK INSTANCE: OK
2024-12-19 06:24:26 [INFO] - Queue count: 0 0 0 0 0
2024-12-19 06:24:26 [INFO] - Main connection closed
2024-12-19 06:24:26 [INFO] - Finished dump at: 2024-12-19 06:24:26

**Comment by billy522** [comment]
**PROCESSLIST**
```
mysql> SHOW PROCESSLIST;
+-------+----------------------+----------------------------------------------------------------+---------+---------+--------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
| Id    | User                 | Host                                                           | db      | Command | Time   | State                                       | Info                                                                                                 |
+-------+----------------------+----------------------------------------------------------------+---------+---------+--------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
|     5 | system user          | connecting host                                                | NULL    | Connect | 248073 | Waiting for source to send event            | NULL                                                                                                 |
|    10 | event_scheduler      | localhost                                                      | NULL    | Daemon  | 248073 | Waiting on empty queue                      | NULL                                                                                                 |
|    17 | pre-proxysql_monitor | mysql-percona-proxysql.c.aaa-stag.internal:55666           | NULL    | Sleep   |      6 |                                             | NULL                                                                                                 |
|    19 | pre-proxysql_monitor | mysql-percona-proxysql-1.c.aaa-stag.internal:60882         | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
|    20 | pre-proxysql_monitor | mysql-percona-proxysql-2.c.aaa-stag.internal:54856         | NULL    | Sleep   |      9 |                                             | NULL                                                                                                 |
|    22 | orchestrator         | mysql-percona-monitoring-machine.c.aaa-stag.internal:45328 | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
|    23 | orchestrator         | mysql-percona-monitoring-machine.c.aaa-stag.internal:45330 | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
|    24 | orchestrator         | mysql-percona-monitoring-machine.c.aaa-stag.internal:45332 | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
| 49908 | root                 | localhost                                                      | NULL    | Sleep   |   1028 |                                             | NULL                                                                                                 |
| 49909 | root                 | localhost                                                      | aaa | Query   |    264 | executing                                   | SELECT /*!40001 SQL_NO_CACHE */ * FROM `aaa`.`db1`  WHERE (`id` IS NULL OR(0 <= `id` AND `id |
| 49910 | root                 | localhost                                                      | percona | Query   |    253 | executing                                   | SELECT /*!40001 SQL_NO_CACHE */ * FROM `aaa`.`db1`  WHERE (390000000 <= `id` AND `id` <= 419 |
| 49911 | root                 | localhost                                                      | sys     | Query   |    264 | executing                                   | SELECT /*!40001 SQL_NO_CACHE */ * FROM `aaa`.`db1`  WHERE (780000000 <= `id` AND `id` <= 809 |
| 49912 | root                 | localhost                                                      | sbtest  | Query   |    667 | executing                                   | SELECT /*!40001 SQL_NO_CACHE */ * FROM `aaa`.`db2`                                |
| 49913 | system user          |                                                                | NULL    | Query   |   1020 | Waiting for dependent transaction to commit | NULL                                                                                                 |
| 49914 | system user          |                                                                |         | Connect |   1025 | Waiting for backup lock                     | NULL                                                                                                 |
| 49915 | system user          |                                                                | NULL    | Connect |   1028 | Waiting for an event from Coordinator       | NULL                                                                                                 |
| 49916 | system user          |                                                                | NULL    | Connect |   1028 | Waiting for an event from Coordinator       | NULL                                                                                                 |
| 49917 | system user          |                                                                | NULL    | Connect |   1028 | Waiting for an event from Coordinator       | NULL                                                                                                 |
| 50115 | pmm                  | localhost                                                      | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
| 50116 | pmm                  | localhost                                                      | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
| 50119 | sre                  | tf-preprod-vpn.c.aaa-stag.internal:55709                   | NULL    | Query   |      0 | init                                        | SHOW PROCESSLIST                                                                                     |
| 50125 | pmm                  | localhost                                                      | NULL    | Sleep   |      0 |                                             | NULL                                                                                                 |
+-------+----------------------+----------------------------------------------------------------+---------+---------+--------+---------------------------------------------+------------------------------------------------------------------------------------------------------+
22 rows in set, 1 warning (0.01 sec)
```

**Comment by billy522** [comment]
**SLAVE STATUS**
```
mysql> SHOW SLAVE STATUS\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for source to send event
                  Master_Host: 10.140.0.3
                  Master_User: replicator
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.007305
          Read_Master_Log_Pos: 108430852
               Relay_Log_File: new-stag-mysql-gift-oregon-7-relay-bin.000892
                Relay_Log_Pos: 108237418
        Relay_Master_Log_File: mysql-bin.007305
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 108237202
              Relay_Log_Space: 108431348
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 1152
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 4294967295
                  Master_UUID: 96eeeb72-ac7c-11eb-9117-42010a8c0003
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Waiting for dependent transaction to commit
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
       Master_public_key_path:
        Get_master_public_key: 0
            Network_Namespace:
1 row in set, 1 warning (0.01 sec)
```
