### ISSUE TITLE
[BUG] Dolt version support did not work

### ISSUE THREAD

**Issue by timsehn** [mydumper/mydumper#1725]
**Describe the bug**

Dolt support was added in this commit: https://github.com/mydumper/mydumper/commit/bb831fbc1c21823ece65da90c660824ebd7a8bf6#diff-f5832cbf75dac15c61a7cd48136ebb3e50da3627f64e8e933484b8ac459387a4R197

But it doesn't work. Running mydumper against a running Dolt produces:

```
$ mydumper -h 127.0.0.1 -P 4000 -u root -p '' --protocol tcp --database transparency-in-pricing

** (mydumper:27890): CRITICAL **: 11:36:09.898: Cannot detect server type
```

Thanks for adding Dolty support but I think we missed a case.

**To Reproduce**

1. Install Dolt: https://docs.dolthub.com/introduction/installation
1. Clone a database from DoltHub: https://www.dolthub.com/profile/discover
2. cd into the database directory.
3. Make the following config.yaml:
```yaml
log_level: info

behavior:
  read_only: false
  autocommit: true

user:
  name: root
  password: ""

listener:
  host: localhost
  port: 4000
  max_connections: 100
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
  tls_key: "/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/servercfg/testdata/chain_key.pem"	
  tls_cert: "/Users/timsehn/dolthub/git/dolt/go/libraries/doltcore/servercfg/testdata/chain_cert.pem"
  require_secure_transport: true
```
NOTE: The key and cert are included in the Dolt source (https://github.com/dolthub/dolt) so you can clone that locally if you don;'t have a key and cert to test with.
4. Start the dolt server using `dolt sql-server --config=config.yaml`
5. In another shell run mydumper: mydumper -h 127.0.0.1 -P 4000 -u root -p '' --protocol tcp --database <db>`

**What mydumper and myloader version has been used?**

Latest installed via Homebrew.

```
$ mydumper --version 
mydumper v0.17.1-1, built against MariaDB 10.8.8 with SSL support
```
