### ISSUE TITLE
Anonymized  dump

### ISSUE THREAD

**Issue by carlosmuller** [mydumper/mydumper#364]
Hi thanks for the super software!
What do you guys think about a option to anonymze some columns and tables?

**Comment by davidducos** [comment]
Hi @carlosmuller,
Interesting... in mydumper (export stage)? myloader (import stage)? both? How we determine the columns? filtering options? hooks?

**Comment by carlosmuller** [comment]
I am thinking in the export stage so the real data never "escape" but may be a little difficult.
I was thing in some config file with tables and columns an some options like auto generate, empty, and other generators, but for initial release could be random_unique, random, empty  and fixed, something like this:

```
User:
   name: random
   username: random_unique
   document: empty
   createdAt: '2021-06-18'
```
