### ISSUE TITLE
Replication breaking with multi-master replication

### ISSUE THREAD

**Issue by consolibyte** [mydumper/mydumper#789]
**Describe the bug**

We are running `mydumper` on a replica server, which has multiple masters. `mydumper` seems to be breaking replication, and I'm struggling to understand why or how it could be doing this. 

Are there any known issues with running `mydumper` on a replica, or a replica of multiple masters? 

We are ending up with errors like this: 

```
*************************** 3. row ***************************
               Connection_name: topgun
               Slave_SQL_State: 
                Slave_IO_State: Waiting for master to send event
                   Master_Host: db12.msp1.example.com
                   Master_User: replication_user
                   Master_Port: 3306
                 Connect_Retry: 10
               Master_Log_File: mariadb-bin.010441
           Read_Master_Log_Pos: 273105474
                Relay_Log_File: mysqld-relay-bin-topgun.000002
                 Relay_Log_Pos: 4
         Relay_Master_Log_File: mariadb-bin.010407
              Slave_IO_Running: Yes
             Slave_SQL_Running: No
               Replicate_Do_DB: 
           Replicate_Ignore_DB: 
            Replicate_Do_Table: 
        Replicate_Ignore_Table: 
       Replicate_Wild_Do_Table: 
   Replicate_Wild_Ignore_Table: 
                    Last_Errno: 1062
                    Last_Error: Error 'Duplicate entry '44847680' for key 'PRIMARY'' on query. Default database: 'example_i1881'. Query: 'INSERT INTO 
				log_api
				( msg, uuid, log_datetime, is_internal )
			VALUES
				(  'Response: {\n    \"code\": 200,\n    \"status\": \"OK\",\n    \"message\": \"\",\n    \"details\": {},\n    \"response\": [\n        {\n            \"superuser_id\": 1,\n            \"external_key\": \"dev1#5795db42d716b4.30957512\",\n            \"token\": \"u8h34lg467b4\",\n            \"company\": \"DEMO TEST\",\n            \"bill_addr1\": \"\",\n            \"bill_addr2\": \"\",\n            \"bill_addr3\": null,\n            \"bill_city\": \"\",\n            \"bill_state\": \"\",\n            \"bill_postcode\": \"\",\n            \"bill_country\": \"United States\",\n            \"bill_notes\": null,\n            \"ship_addr1\": null,\n            \"ship_addr2\": null,\n            \"ship_addr3\": null,\n            \"ship_city\": null,\n            \"ship_state\": null,\n            \"ship_postcode\": null,\
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 535550444
               Relay_Log_Space: 18016898217
               Until_Condition: None
                Until_Log_File: 
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File: 
            Master_SSL_CA_Path: 
               Master_SSL_Cert: 
             Master_SSL_Cipher: 
                Master_SSL_Key: 
         Seconds_Behind_Master: NULL
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 0
                 Last_IO_Error: 
                Last_SQL_Errno: 1062
                Last_SQL_Error: Error 'Duplicate entry '44847680' for key 'PRIMARY'' on query. Default database: 'example_i1881'. Query: 'INSERT INTO 
				log_api
				( msg, uuid, log_datetime, is_internal )
			VALUES
				(  'Response: {\n    \"code\": 200,\n    \"status\": \"OK\",\n    \"message\": \"\",\n    \"details\": {},\n    \"response\": [\n        {\n            \"superuser_id\": 1,\n            \"external_key\": \"dev1#5795db42d716b4.30957512\",\n            \"token\": \"u8h34lg467b4\",\n            \"company\": \"DEMO TEST\",\n            \"bill_addr1\": \"\",\n            \"bill_addr2\": \"\",\n            \"bill_addr3\": null,\n            \"bill_city\": \"\",\n            \"bill_state\": \"\",\n            \"bill_postcode\": \"\",\n            \"bill_country\": \"United States\",\n            \"bill_notes\": null,\n            \"ship_addr1\": null,\n            \"ship_addr2\": null,\n            \"ship_addr3\": null,\n            \"ship_city\": null,\n            \"ship_state\": null,\n            \"ship_postcode\": null,\
   Replicate_Ignore_Server_Ids: 
              Master_Server_Id: 12
                Master_SSL_Crl: 
            Master_SSL_Crlpath: 
                    Using_Gtid: Slave_Pos
                   Gtid_IO_Pos: 1-11-4685415522,0-7-18740482264,2-12-3295415216
       Replicate_Do_Domain_Ids: 
   Replicate_Ignore_Domain_Ids: 
                 Parallel_Mode: conservative
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State: 
              Slave_DDL_Groups: 13262
Slave_Non_Transactional_Groups: 6171181
    Slave_Transactional_Groups: 47743384
          Retried_transactions: 0
            Max_relay_log_size: 536870912
          Executed_log_entries: 172069024
     Slave_received_heartbeats: 0
        Slave_heartbeat_period: 900.000
                Gtid_Slave_Pos: 0-7-18740482264,1-11-4685423789,2-12-3288932755,4-14-1
3 rows in set (0.001 sec)
```

Another one we saw was this: 

```
Last_SQL_Error: Error 'Table 'example_i8896.session' doesn't exist' on query. Default database: 'example_i8896'. Query: 'UPDATE session SET touch_datetime = '2022-07-27 13:19:50' , touch_ipaddr = '173.169.40.193'  WHERE sid = '61fabc108a9b02ec5ba73667cf2d4cc4ac282494''
```

It's very confusing to me because my understanding is that binary log statements shouldn't be able to execute twice to result in that duplicate row, and for the second error the table _did_ exist on the replica. 

Does `mydumper` mess with GTID positions or something that could be causing transactions to try to run twice on the replica?

**To Reproduce**

Need to get this from our team. 

```
mydumper 0.12.3-3, built against MySQL 5.7.37-40
```

**Expected behavior**

Replication doesn't break. :-) 

**Log**

I will try to get this from our team. They did drop a screenshot with lots of other weird errors, but I don't have the full log. Will try to get these! 

![image](https://user-images.githubusercontent.com/248989/182024871-8f03a781-dbba-415b-bce5-07484eea9c3e.png)

**Environment (please complete the following information):**
 
```
keithpalmer@DB14:~$ sudo uname -a
Linux DB14 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

```
mysql --version
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
